### PR TITLE
Support basic auth

### PR DESCRIPTION
**Pull request by goyerl**
I recently started using chaos toolkit.  My spring boot apps use [spring security](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-security) to secure actuator endpoints.  

This adds support for basic auth.

### CODE REVIEW

**Comment by ciaransweet** [comment]
Hey @goyerl thanks for the PR! 

Really sorry it's taken so long for someone to get back to you on this, looks like the repo didn't get much attention for a good while

I've recently just got working on this project and have made a few quality of life improvements around contributing - is this still a change you'd like within the extension?

**Comment by goyerl** [comment]
> 
> 
> Hey @goyerl thanks for the PR!
> 
> Really sorry it's taken so long for someone to get back to you on this, looks like the repo didn't get much attention for a good while
> 
> I've recently just got working on this project and have made a few quality of life improvements around contributing - is this still a change you'd like within the extension?

@ciaranevans I ended up creating something specific to my environment that works very similar to what I included in this PR.  I thought others might want the same functionality so I opened this PR.  I would be happy to make any updates if it can help out the project.

**Comment by ciaransweet** [comment]
@goyerl I certainly expect this is something someone would use!

**Comment by ciaransweet** [comment]
Sorry for the resurrection - Cleaning up my https://github.com/pulls/mentioned list and this is the _last_ one I have. 

Unfortunately unless this is closed, I think I'm stuck with it 😆 

@goyerl if you're still interested in pursuing this could you bring it back? Else could this PR be closed? It's ~3 years old 

cc @Lawouach

**Pull request closed without merging**
